// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "music-streaming/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockMediaBrowsingRepository is an autogenerated mock type for the MediaBrowsingRepository type
type MockMediaBrowsingRepository struct {
	mock.Mock
}

type MockMediaBrowsingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaBrowsingRepository) EXPECT() *MockMediaBrowsingRepository_Expecter {
	return &MockMediaBrowsingRepository_Expecter{mock: &_m.Mock}
}

// CreateAlbum provides a mock function with given fields: ctx, album
func (_m *MockMediaBrowsingRepository) CreateAlbum(ctx context.Context, album domain.Album) (domain.Album, error) {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlbum")
	}

	var r0 domain.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Album) (domain.Album, error)); ok {
		return rf(ctx, album)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Album) domain.Album); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Get(0).(domain.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Album) error); ok {
		r1 = rf(ctx, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_CreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlbum'
type MockMediaBrowsingRepository_CreateAlbum_Call struct {
	*mock.Call
}

// CreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album domain.Album
func (_e *MockMediaBrowsingRepository_Expecter) CreateAlbum(ctx interface{}, album interface{}) *MockMediaBrowsingRepository_CreateAlbum_Call {
	return &MockMediaBrowsingRepository_CreateAlbum_Call{Call: _e.mock.On("CreateAlbum", ctx, album)}
}

func (_c *MockMediaBrowsingRepository_CreateAlbum_Call) Run(run func(ctx context.Context, album domain.Album)) *MockMediaBrowsingRepository_CreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Album))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateAlbum_Call) Return(_a0 domain.Album, _a1 error) *MockMediaBrowsingRepository_CreateAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateAlbum_Call) RunAndReturn(run func(context.Context, domain.Album) (domain.Album, error)) *MockMediaBrowsingRepository_CreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtist provides a mock function with given fields: ctx, artist
func (_m *MockMediaBrowsingRepository) CreateArtist(ctx context.Context, artist domain.Artist) (domain.Artist, error) {
	ret := _m.Called(ctx, artist)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtist")
	}

	var r0 domain.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Artist) (domain.Artist, error)); ok {
		return rf(ctx, artist)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Artist) domain.Artist); ok {
		r0 = rf(ctx, artist)
	} else {
		r0 = ret.Get(0).(domain.Artist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Artist) error); ok {
		r1 = rf(ctx, artist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_CreateArtist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtist'
type MockMediaBrowsingRepository_CreateArtist_Call struct {
	*mock.Call
}

// CreateArtist is a helper method to define mock.On call
//   - ctx context.Context
//   - artist domain.Artist
func (_e *MockMediaBrowsingRepository_Expecter) CreateArtist(ctx interface{}, artist interface{}) *MockMediaBrowsingRepository_CreateArtist_Call {
	return &MockMediaBrowsingRepository_CreateArtist_Call{Call: _e.mock.On("CreateArtist", ctx, artist)}
}

func (_c *MockMediaBrowsingRepository_CreateArtist_Call) Run(run func(ctx context.Context, artist domain.Artist)) *MockMediaBrowsingRepository_CreateArtist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Artist))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateArtist_Call) Return(_a0 domain.Artist, _a1 error) *MockMediaBrowsingRepository_CreateArtist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateArtist_Call) RunAndReturn(run func(context.Context, domain.Artist) (domain.Artist, error)) *MockMediaBrowsingRepository_CreateArtist_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCover provides a mock function with given fields: ctx, cover
func (_m *MockMediaBrowsingRepository) CreateCover(ctx context.Context, cover domain.Cover) (domain.Cover, error) {
	ret := _m.Called(ctx, cover)

	if len(ret) == 0 {
		panic("no return value specified for CreateCover")
	}

	var r0 domain.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cover) (domain.Cover, error)); ok {
		return rf(ctx, cover)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Cover) domain.Cover); ok {
		r0 = rf(ctx, cover)
	} else {
		r0 = ret.Get(0).(domain.Cover)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Cover) error); ok {
		r1 = rf(ctx, cover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_CreateCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCover'
type MockMediaBrowsingRepository_CreateCover_Call struct {
	*mock.Call
}

// CreateCover is a helper method to define mock.On call
//   - ctx context.Context
//   - cover domain.Cover
func (_e *MockMediaBrowsingRepository_Expecter) CreateCover(ctx interface{}, cover interface{}) *MockMediaBrowsingRepository_CreateCover_Call {
	return &MockMediaBrowsingRepository_CreateCover_Call{Call: _e.mock.On("CreateCover", ctx, cover)}
}

func (_c *MockMediaBrowsingRepository_CreateCover_Call) Run(run func(ctx context.Context, cover domain.Cover)) *MockMediaBrowsingRepository_CreateCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Cover))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateCover_Call) Return(_a0 domain.Cover, _a1 error) *MockMediaBrowsingRepository_CreateCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateCover_Call) RunAndReturn(run func(context.Context, domain.Cover) (domain.Cover, error)) *MockMediaBrowsingRepository_CreateCover_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSong provides a mock function with given fields: ctx, song
func (_m *MockMediaBrowsingRepository) CreateSong(ctx context.Context, song domain.Song) (domain.Song, error) {
	ret := _m.Called(ctx, song)

	if len(ret) == 0 {
		panic("no return value specified for CreateSong")
	}

	var r0 domain.Song
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Song) (domain.Song, error)); ok {
		return rf(ctx, song)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Song) domain.Song); ok {
		r0 = rf(ctx, song)
	} else {
		r0 = ret.Get(0).(domain.Song)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Song) error); ok {
		r1 = rf(ctx, song)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_CreateSong_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSong'
type MockMediaBrowsingRepository_CreateSong_Call struct {
	*mock.Call
}

// CreateSong is a helper method to define mock.On call
//   - ctx context.Context
//   - song domain.Song
func (_e *MockMediaBrowsingRepository_Expecter) CreateSong(ctx interface{}, song interface{}) *MockMediaBrowsingRepository_CreateSong_Call {
	return &MockMediaBrowsingRepository_CreateSong_Call{Call: _e.mock.On("CreateSong", ctx, song)}
}

func (_c *MockMediaBrowsingRepository_CreateSong_Call) Run(run func(ctx context.Context, song domain.Song)) *MockMediaBrowsingRepository_CreateSong_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Song))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateSong_Call) Return(_a0 domain.Song, _a1 error) *MockMediaBrowsingRepository_CreateSong_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_CreateSong_Call) RunAndReturn(run func(context.Context, domain.Song) (domain.Song, error)) *MockMediaBrowsingRepository_CreateSong_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlbumByID provides a mock function with given fields: ctx, id
func (_m *MockMediaBrowsingRepository) GetAlbumByID(ctx context.Context, id int) (domain.Album, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbumByID")
	}

	var r0 domain.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Album, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Album); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Album)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_GetAlbumByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbumByID'
type MockMediaBrowsingRepository_GetAlbumByID_Call struct {
	*mock.Call
}

// GetAlbumByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMediaBrowsingRepository_Expecter) GetAlbumByID(ctx interface{}, id interface{}) *MockMediaBrowsingRepository_GetAlbumByID_Call {
	return &MockMediaBrowsingRepository_GetAlbumByID_Call{Call: _e.mock.On("GetAlbumByID", ctx, id)}
}

func (_c *MockMediaBrowsingRepository_GetAlbumByID_Call) Run(run func(ctx context.Context, id int)) *MockMediaBrowsingRepository_GetAlbumByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_GetAlbumByID_Call) Return(_a0 domain.Album, _a1 error) *MockMediaBrowsingRepository_GetAlbumByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_GetAlbumByID_Call) RunAndReturn(run func(context.Context, int) (domain.Album, error)) *MockMediaBrowsingRepository_GetAlbumByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtistByID provides a mock function with given fields: ctx, id
func (_m *MockMediaBrowsingRepository) GetArtistByID(ctx context.Context, id int) (domain.Artist, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetArtistByID")
	}

	var r0 domain.Artist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Artist, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Artist); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Artist)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_GetArtistByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtistByID'
type MockMediaBrowsingRepository_GetArtistByID_Call struct {
	*mock.Call
}

// GetArtistByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMediaBrowsingRepository_Expecter) GetArtistByID(ctx interface{}, id interface{}) *MockMediaBrowsingRepository_GetArtistByID_Call {
	return &MockMediaBrowsingRepository_GetArtistByID_Call{Call: _e.mock.On("GetArtistByID", ctx, id)}
}

func (_c *MockMediaBrowsingRepository_GetArtistByID_Call) Run(run func(ctx context.Context, id int)) *MockMediaBrowsingRepository_GetArtistByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_GetArtistByID_Call) Return(_a0 domain.Artist, _a1 error) *MockMediaBrowsingRepository_GetArtistByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_GetArtistByID_Call) RunAndReturn(run func(context.Context, int) (domain.Artist, error)) *MockMediaBrowsingRepository_GetArtistByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoverByID provides a mock function with given fields: ctx, id
func (_m *MockMediaBrowsingRepository) GetCoverByID(ctx context.Context, id string) (domain.Cover, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCoverByID")
	}

	var r0 domain.Cover
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Cover, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Cover); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Cover)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_GetCoverByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoverByID'
type MockMediaBrowsingRepository_GetCoverByID_Call struct {
	*mock.Call
}

// GetCoverByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMediaBrowsingRepository_Expecter) GetCoverByID(ctx interface{}, id interface{}) *MockMediaBrowsingRepository_GetCoverByID_Call {
	return &MockMediaBrowsingRepository_GetCoverByID_Call{Call: _e.mock.On("GetCoverByID", ctx, id)}
}

func (_c *MockMediaBrowsingRepository_GetCoverByID_Call) Run(run func(ctx context.Context, id string)) *MockMediaBrowsingRepository_GetCoverByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_GetCoverByID_Call) Return(_a0 domain.Cover, _a1 error) *MockMediaBrowsingRepository_GetCoverByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_GetCoverByID_Call) RunAndReturn(run func(context.Context, string) (domain.Cover, error)) *MockMediaBrowsingRepository_GetCoverByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSongByID provides a mock function with given fields: ctx, id
func (_m *MockMediaBrowsingRepository) GetSongByID(ctx context.Context, id int) (domain.Song, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSongByID")
	}

	var r0 domain.Song
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (domain.Song, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) domain.Song); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Song)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaBrowsingRepository_GetSongByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSongByID'
type MockMediaBrowsingRepository_GetSongByID_Call struct {
	*mock.Call
}

// GetSongByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockMediaBrowsingRepository_Expecter) GetSongByID(ctx interface{}, id interface{}) *MockMediaBrowsingRepository_GetSongByID_Call {
	return &MockMediaBrowsingRepository_GetSongByID_Call{Call: _e.mock.On("GetSongByID", ctx, id)}
}

func (_c *MockMediaBrowsingRepository_GetSongByID_Call) Run(run func(ctx context.Context, id int)) *MockMediaBrowsingRepository_GetSongByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockMediaBrowsingRepository_GetSongByID_Call) Return(_a0 domain.Song, _a1 error) *MockMediaBrowsingRepository_GetSongByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaBrowsingRepository_GetSongByID_Call) RunAndReturn(run func(context.Context, int) (domain.Song, error)) *MockMediaBrowsingRepository_GetSongByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaBrowsingRepository creates a new instance of MockMediaBrowsingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaBrowsingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaBrowsingRepository {
	mock := &MockMediaBrowsingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
