// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "music-streaming/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserManagementRepository is an autogenerated mock type for the UserManagementRepository type
type MockUserManagementRepository struct {
	mock.Mock
}

type MockUserManagementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManagementRepository) EXPECT() *MockUserManagementRepository_Expecter {
	return &MockUserManagementRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockUserManagementRepository) CreateUser(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManagementRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserManagementRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserManagementRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUserManagementRepository_CreateUser_Call {
	return &MockUserManagementRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUserManagementRepository_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserManagementRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *MockUserManagementRepository_CreateUser_Call) Return(_a0 error) *MockUserManagementRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManagementRepository_CreateUser_Call) RunAndReturn(run func(context.Context, domain.User) error) *MockUserManagementRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, username
func (_m *MockUserManagementRepository) DeleteUser(ctx context.Context, username string) error {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManagementRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserManagementRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserManagementRepository_Expecter) DeleteUser(ctx interface{}, username interface{}) *MockUserManagementRepository_DeleteUser_Call {
	return &MockUserManagementRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, username)}
}

func (_c *MockUserManagementRepository_DeleteUser_Call) Run(run func(ctx context.Context, username string)) *MockUserManagementRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserManagementRepository_DeleteUser_Call) Return(_a0 error) *MockUserManagementRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManagementRepository_DeleteUser_Call) RunAndReturn(run func(context.Context, string) error) *MockUserManagementRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, username
func (_m *MockUserManagementRepository) GetUser(ctx context.Context, username string) (domain.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagementRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserManagementRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserManagementRepository_Expecter) GetUser(ctx interface{}, username interface{}) *MockUserManagementRepository_GetUser_Call {
	return &MockUserManagementRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, username)}
}

func (_c *MockUserManagementRepository_GetUser_Call) Run(run func(ctx context.Context, username string)) *MockUserManagementRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserManagementRepository_GetUser_Call) Return(_a0 domain.User, _a1 error) *MockUserManagementRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagementRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *MockUserManagementRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx
func (_m *MockUserManagementRepository) GetUsers(ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserManagementRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUserManagementRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserManagementRepository_Expecter) GetUsers(ctx interface{}) *MockUserManagementRepository_GetUsers_Call {
	return &MockUserManagementRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx)}
}

func (_c *MockUserManagementRepository_GetUsers_Call) Run(run func(ctx context.Context)) *MockUserManagementRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserManagementRepository_GetUsers_Call) Return(_a0 []domain.User, _a1 error) *MockUserManagementRepository_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserManagementRepository_GetUsers_Call) RunAndReturn(run func(context.Context) ([]domain.User, error)) *MockUserManagementRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, username, user
func (_m *MockUserManagementRepository) UpdateUser(ctx context.Context, username string, user domain.User) error {
	ret := _m.Called(ctx, username, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.User) error); ok {
		r0 = rf(ctx, username, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserManagementRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserManagementRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - user domain.User
func (_e *MockUserManagementRepository_Expecter) UpdateUser(ctx interface{}, username interface{}, user interface{}) *MockUserManagementRepository_UpdateUser_Call {
	return &MockUserManagementRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, username, user)}
}

func (_c *MockUserManagementRepository_UpdateUser_Call) Run(run func(ctx context.Context, username string, user domain.User)) *MockUserManagementRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.User))
	})
	return _c
}

func (_c *MockUserManagementRepository_UpdateUser_Call) Return(_a0 error) *MockUserManagementRepository_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserManagementRepository_UpdateUser_Call) RunAndReturn(run func(context.Context, string, domain.User) error) *MockUserManagementRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserManagementRepository creates a new instance of MockUserManagementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManagementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManagementRepository {
	mock := &MockUserManagementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
