// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Username            pgtype.Text
	Password            string
	Email               string
	Ldapauthenticated   bool
	Adminrole           bool
	Settingsrole        bool
	Streamrole          bool
	Jukeboxrole         bool
	Downloadrole        bool
	Uploadrole          bool
	Playlistrole        bool
	Coverartrole        bool
	Commentrole         bool
	Podcastrole         bool
	Sharerole           bool
	Videoconversionrole bool
	Musicfolderid       []byte
}
